### ISSUE TITLE
Handling of unsupported filters

### ISSUE THREAD

**Issue by out-of-range** [beetbox/aura#25]
Hello,

I'm just wondering what a server should do if a client requests filtering of resources by an unsupported key. For example if the client asks for `/aura/tracks?filter[bpm]=100`, but the server doesn't support the optional `bpm` attribute.

The options I've come up with are:
- ignore the filter
- return an error (maybe `501 Not Implemented`)
- return an empty data array (like it would if there were no matching tracks)

**Comment by sampsyo** [comment]
That's a very good question. All of these seem feasible…

Thinking through how this would play out in beets, for example: because we have flexattrs, we don't really have a notion of "supported" and "unsupported" fields. Anything *might* be a supported field, if even a single track has that attribute. So for beets's purposes alone, it would certainly be convenient if we picked option 3, i.e., return an empty result—because that's how `beet ls` already works.

The only downside I can see to that is that it might prevent clients from doing some sort of "probing" to see which fields are available, responding to 501 errors by backing off from certain searches. But I'm not actually sure that's very useful. Maybe let's go with the empty-result option for now and keep the door open to errors in the future?

**Comment by out-of-range** [comment]
Yep that makes sense. I agree that it's not useful for probing; if that functionality is needed it would be better/easier to just provide it up front. I made a pull request (#26) to clarify a bit what should happen in the discussed situation.
